[project]
name = "life-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "matplotlib>=3.10.7",
    "mesa>=3.3.0",
    "networkx>=3.5",
    "solara>=1.52.0",
]
